name: WebDriverIO TypeScript BDD CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.17.6
        cache: 'npm'
    - run: npm install
    - run: npm run smoke

  regression:
    needs: [smoke]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.17.6
        cache: 'npm'
    - run: npm install
    - run: npm run regression

    - name: Generate Cucumber HTML Report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: CucumberHTMLReport
        path: reports/html
